version: 2.1
defaults: &defaults
  working_directory: ~/dems
  docker:
    - image: robcresswell/circleci-node-alpine
commands:
  install_deps:
    description: Install dependencies (from cache, if possible)
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-{{ .Branch }}-
            - yarn-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
jobs:
  snyk:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run snyk
          command: npx snyk test
  test:
    <<: *defaults
    steps:
      - install_deps
      - run:
          name: Run tests
          command: yarn test
      - store_artifacts:
          path: reports/coverage
      - store_test_results:
          path: reports
  lint:
    <<: *defaults
    steps:
      - install_deps
      - run:
          name: Run linting tasks
          command: yarn lint
  release:
    <<: *defaults
    steps:
      - install_deps
      - run: yarn build
      - run: npx semantic-release
workflows:
  version: 2
  test_and_release:
    jobs:
      - snyk
      - test
      - lint
      - release:
          requires:
            - lint
            - test
